verilog:
	iverilog -o tb_lavadora.out tb_lavadora.v
	vvp tb_lavadora.out
	gtkwave gtkwave_lavadora.vcd
borrar:
	rm contador_lavadora.v
	rm lavadora.v
	rm tester_lavadora.v
	rm tb_lavadora.v
	rm tb_lavadora.out
	rm gtkwave_lavadora.vcd

borrar .exe:
	rm tb_lavadora.out
	rm gtkwave_lavadora.vcd

contador:
	cat contador_lavadora.v

lavadora:
	cat lavadora.v

tester:
	cat tester_lavadora.v

tb:
	cat tb_lavadora.v


