verilog:
	iverilog -o calculadora.out testbench.v
	vvp calculadora.out
	gtkwave tb_calculadora8bit.vcd
borrar:
	rm tb_calculadora8bit.v
	rm testbench.v
	rm tester.v
	rm calculadora.out
	rm calculadora8bit.v

borrar .exe:
	rm calculadora.out
	rm tb_calculadora8bit.vcd