verilog:
	iverilog -o tb_semaforo.out tb_semaforo.v
	vvp tb_semaforo.out
	gtkwave gtkwave_semaforo.vcd
borrar:
	rm semaforo.v
	rm tester_semaforo.v
	rm tb_semaforo.v
	rm tb_semaforo.out
	rm gtkwave_semaforo.vcd

borrar.exe:
	rm tb_semaforo.out
	rm gtkwave_semaforo.vcd

semaforo:
	cat semaforo.v

tester:
	cat tester_semaforo.v

tb:
	cat tb_semaforo.v

